### ISSUE TITLE
wrong digit representation for underscore sequence naming 

### ISSUE THREAD

**Issue by hdd** [4degrees/clique#15]
while parsing a sequence not divided with dots, the parser is not able to identify the correct amount of digits:
<code>
\<Collection "/home/hdd/devel/TEST_VFX_RAW/TEST_VFX_SC0100/TEST_VFX_SC0100_SH0100_V0/TST_VFX_SC0100_SH0100_V0_P1_%d.dpx [1001-1722]"\>
</code>
where it should have been:
<code>
\<Collection "/home/hdd/devel/TEST_VFX_RAW/TEST_VFX_SC0100/TEST_VFX_SC0100_SH0100_V0/TST_VFX_SC0100_SH0100_V0_P1_%04d.dpx [1001-1722]"\>
</code>

I'm using clique from ftrack to publish sequences, and having %d , make nuke think that is a one digit sequence, so , rather than trying to import _1001.dpx it looks for _1.dpx

Cheers.
L.

**Comment by martinpengellyphillips** [comment]
Ok, this seems to be the same as #10. Closing for same reason (see comment on that issue).
