### ISSUE TITLE
Make It Easier To Copy File Collections

### ISSUE THREAD

**Issue by elveatles** [4degrees/clique#19]
As far as I can tell, there is no easy way to copy a collection of files to another place with a different head. For example, in the code below, I had to copy the source code in collection to get formatted_index, srcItem, and dstItem.

    import os
    import shutil
    import clique

    srcDir = '/src/dir'
    dstDir = '/dst/dir'
    srcFiles = os.listdir(srcDir)
    collections = clique.assemble(srcFiles)[0]
    srcCollection = collections[0]
    for i in srcCollection.indexes:
        dstHead = 'rename.'
        formatted_index = '{0:0{1}d}'.format(i, srcCollection.padding)
        srcItem = '{0}{1}{2}'.format(srcCollection.head, formatted_index, srcCollection.tail)
        dstItem = '{0}{1}{2}'.format(dstHead, formatted_index, srcCollection.tail)
        src = os.path.join(srcDir, srcItem)
        dst = os.path.join(dstDir, dstItem)
        shutil.copy2(src, dst)

**Comment by martinpengellyphillips** [comment]
Be aware that you can copy and manipulate collections which might be simpler:

```python
import copy

import clique

collections, _ = clique.assemble(['/path/to/frames.{:04d}.jpg'.format(index) for index in range(10)])
source_collection = collections[0]

target_collection = copy.copy(source_collection)
target_collection.head = source_collection.head.replace('frames.', 'rename.')

for source_path, target_path in zip(source_collection, target_collection):
    print 'Copy ', source_path, '->', target_path

# Copy  /path/to/frames.0000.jpg -> /path/to/rename.0000.jpg
# Copy  /path/to/frames.0001.jpg -> /path/to/rename.0001.jpg
# Copy  /path/to/frames.0002.jpg -> /path/to/rename.0002.jpg
# ...
```

Note that Clique is designed to be a fairly simple low level library that other tools can build on top of so I'm not sure whether bundling utilities for copying sequences would make sense. Perhaps a separate project could be started?

**Comment by elveatles** [comment]
Your example was pretty much what I was looking for. It would still be nice to be able to get the formatted name of an arbitrary index though.

**Comment by martinpengellyphillips** [comment]
Cool.

I'll close this ticket, but feel free to start a new one for the formatting of arbitrary index though if you want.
